# Generated by Django 3.0.8 on 2020-07-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_auto_20200729_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevice',
            name='circuit',
            field=models.IntegerField(default=0),
        ),
    ]
