# Generated by Django 3.0.8 on 2020-07-29 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_iotdevice_circuit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='iot.Building')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.Person')),
            ],
        ),
    ]
